### PR TITLE
Updated api gateway manager

### PR DESCRIPTION
**Pull request by rovase**
Added a new method to update the integration response for a particular resource at apigateway and then deploy the same to the specified stage.

### CODE REVIEW

**Comment by Shockolate** [comment]
How is this different than making a change to the Integration Response in the Swagger file using the Swagger API Gateway Extensions?

I see no problems with the code

**Comment by rovase** [comment]
There is a specific section called 'responseTemplates' which is not being read from the Swagger file when API Gateway is created using the Swagger file.
In my case I need to update the 'responseTemplates' to take "text/html":"$input.path('$')"
I also tried updating the same at the apigateway using the console and then exported a swagger file out of the apigateway. The exported swagger did not have the corresponding response template section.

**Comment by wparad** [comment]
To get the exported swagger file to contain the `responseTemplates` field you have to use the `Export as Swagger + API Gateway Extensions` instead

**Comment by rovase** [comment]
Hey, that works. I guess I missed out on some step while trying the export. I will check if the same is considered when creating the apigateway from the swagger, and update you guys.

**Comment by Shockolate** [comment]
Also, see here: http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html

**Comment by wparad** [comment]
It should be, I am doing something similar using nodejs library [aws architect](https://github.com/wparad/AWS-Architect/blob/master/lib/ApiGatewayManager.js#L98)

**Comment by rovase** [comment]
Thank you guys, it does work, I made a syntax error on my swagger file.
Hence, the change as part of this pull request is not necessary.

**Pull request closed without merging**
